import { readFileSync, writeFileSync } from "node:fs";
import ts from "typescript";

const sourceFiles = [
  "dateRange",
  "eventNormalizer",
  "formatter",
  "tokenStore",
  "googleAuth",
  "googleCalendar",
  "settings",
  "main",
];

const modules = Object.fromEntries(
  sourceFiles.map((name) => {
    const source = readFileSync(`src/${name}.ts`, "utf8");
    const transpiled = ts.transpileModule(source, {
      compilerOptions: {
        esModuleInterop: true,
        importHelpers: false,
        module: ts.ModuleKind.CommonJS,
        target: ts.ScriptTarget.ES2020,
      },
      fileName: `src/${name}.ts`,
    }).outputText;

    return [`./${name}`, transpiled];
  }),
);

const output = `/*
THIS IS A GENERATED/BUNDLED FILE.
If you want to view the source, visit the GitHub repository for this plugin.
*/

(function() {
  const modules = {
${Object.entries(modules)
  .map(([id, code]) => `    ${JSON.stringify(id)}: function(require, exports, module) {\n${indent(code, 6)}\n    }`)
  .join(",\n")}
  };
  const cache = {};
  function localRequire(id) {
    if (modules[id]) {
      if (!cache[id]) {
        const module = { exports: {} };
        cache[id] = module;
        modules[id](localRequire, module.exports, module);
      }
      return cache[id].exports;
    }
    return require(id);
  }
  module.exports = localRequire("./main");
})();
`;

writeFileSync("main.js", output);

function indent(text, spaces) {
  const padding = " ".repeat(spaces);
  return text
    .trimEnd()
    .split("\n")
    .map((line) => `${padding}${line}`)
    .join("\n");
}
